from .state import AgentState
from ..db_client import DBClient
from .prompts import ANALYSIS_PROMPT
from .prompts import ADVICE_PROMPT
from .prompts import REVIEW_ADVICE_PROMPT

import json
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate

import os

load_dotenv()
api_key = os.getenv("GOOGLE_API_KEY")

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-pro",
    google_api_key=api_key,
    temperature=0.1,
)

def extract_filter_selectivity(plan_json):
    results = []
    def walk(node):
        if "Rows Removed by Filter" in node and "Actual Rows" in node:
            actual = node["Actual Rows"]
            removed = node["Rows Removed by Filter"]
            total = actual + removed
            if total > 0:
                results.append({
                    "node_type": node.get("Node Type", "Unknown"),
                    "relation": node.get("Relation Name", ""),
                    "actual_rows": actual,
                    "rows_removed": removed,
                    "selectivity": round(actual / total, 4)
                })
        for child in node.get("Plans", []):
            walk(child)
    
    if plan_json and len(plan_json) > 0:
        walk(plan_json[0]["Plan"])

    return results


def strip_code_block(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1]
        text = text.rsplit("```", 1)[0]
    return text.strip()


def run_explain_node(state: AgentState):
    # Node 1: Execute EXPLAIN ANALYZE
    dsn = os.getenv("DATABASE_URL")
    if not dsn:
        return {"error": "DATABASE_URL not set"}
    
    db_client = DBClient(dsn)

    original_sql = state.get("original_sql")

    if not original_sql:
        return {"error": "No Original SQL found"}

    try:
        plan = db_client.execute_explain(original_sql)

        return {
            "explain_output": plan,
            "filter_selectivity": extract_filter_selectivity(plan),
            "error": None
        }
    except Exception as e:
        return {
            "error": f"Database Execution Failure: {str(e)}"
        }


def identify_issues(state: AgentState):
    # Node 2: use LLM to identify DB issues from EXPLAIN PLAN
    prompt = ChatPromptTemplate.from_messages([
        ("system", ANALYSIS_PROMPT),
        ("user", "DDL: {ddl}\nExecution_Plan: {execution_plan}\nFilter Selectivity: {filter_selectivity}\nPrevious feedback: {feedback}")
    ])

    chain = prompt | llm

    response = chain.invoke({
        "ddl": state.get("ddl"),
        "execution_plan": state.get("explain_output"),
        "filter_selectivity": state.get("filter_selectivity") or [],
        "feedback": state.get("feedback") or "None"
    })
    
    try:
        issues = json.loads(strip_code_block(response.content))
        return {"issues": issues}
    except json.JSONDecodeError:
        return {"error": f"LLM returned unparseable response: {response.content}"}


def generate_advice(state: AgentState):
    # Node 3: generate advice based on issues found
    prompt = ChatPromptTemplate.from_messages([
        ("system", ADVICE_PROMPT),
        ("user", "SQL: {original_sql}\nIssues: {issues}")
    ])

    chain = prompt | llm

    response = chain.invoke({
        "original_sql": state.get("original_sql"),
        "issues": state.get("issues")
    })

    try:
        result = json.loads(strip_code_block(response.content))
        return {
            "advice": result["advice"],
            "optimized_sql": result["optimized_sql"]
        }
    except (json.JSONDecodeError, KeyError) as e:
        return {"error": f"LLM returned unparseable response: {response.content}"}


def review_advice(state: AgentState):
    # Node 4: review advice generated by previous node
    prompt = ChatPromptTemplate.from_messages([
        ("system", REVIEW_ADVICE_PROMPT),
        ("user", "Advice: {advice}\nOptimized SQL: {optimized_sql}\nIssues: {issues}")
    ])

    chain = prompt | llm

    response = chain.invoke({
        "advice": state.get("advice"),
        "optimized_sql": state.get("optimized_sql"),
        "issues": state.get("issues")
    })

    try:
        result = json.loads(strip_code_block(response.content))
        new_retry_count = (state.get("retry_count") or 0)
        
        if result["verdict"] == "retry":
            new_retry_count += 1

        return {
            "verdict": result["verdict"],
            "feedback": result["feedback"],
            "retry_count": new_retry_count
        }
    except (json.JSONDecodeError, KeyError) as e:
        return {"error": f"LLM returned unparseable response: {response.content}"}


def generate_benchmark_schema(state: AgentState):
    # Node 5: create benchmark schema for testing
    dsn = os.getenv("DATABASE_URL")
    if not dsn:
        return {"error": "DATABASE_URL not set"}
    
    db_client = DBClient(dsn)

    if not state.get("optimized_sql"):
        return {"error": "No optimized SQL to benchmark"}

    table_name = state.get("table_name")
    original_sql = state.get("original_sql")
    suggested_ddl = state.get("optimized_sql")

    try:
        new_plan = db_client.benchmark_in_sandbox(table_name, original_sql, suggested_ddl)
        return {
            "benchmark_result": new_plan
        }
    except Exception as e:
        return {
            "error": f"Database Execution Failure: {str(e)}"
        }
